# Generated by Django 2.0.4 on 2018-04-12 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_received', models.DateTimeField(auto_now_add=True)),
                ('severity_level', models.TextField()),
                ('alert_description', models.TextField()),
                ('show_alert_until', models.BooleanField()),
                ('read_by_user', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_execution', models.DateTimeField(auto_now_add=True)),
                ('command', models.TextField()),
                ('outcome', models.TextField(blank=True, null=True)),
                ('errors', models.BooleanField()),
                ('sent', models.BooleanField()),
                ('completed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=30)),
                ('auth_key', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_key', models.TextField()),
                ('version', models.TextField(blank=True, null=True)),
                ('computer_name', models.TextField(blank=True, null=True)),
                ('operating_system', models.TextField(blank=True, null=True)),
                ('cpu', models.TextField(blank=True, null=True)),
                ('memory', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulseApp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('path', models.TextField()),
                ('log_type', models.TextField()),
                ('time_received', models.DateTimeField(auto_now_add=True)),
                ('process', models.BooleanField()),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulseApp.Computers')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_received', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulseApp.Computers')),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulseApp.Computers'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulseApp.Computers'),
        ),
    ]
